TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.7
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 2
  acc_lim_x: 0.3
  acc_lim_y: 0.3

  yaw_goal_tolerance: 0.5
  xy_goal_difference: 0.25

  holonomic_robot: false
  meter_scoring: true
