global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.1
  static_map: true
  rolling_window: false
  width: 100.0
  height: 100.0
